// @generated by protobuf-ts 2.9.4 with parameter client_grpc1
// @generated from protobuf file "wish.proto" (package "data", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message data.Patch
 */
export interface Patch {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: int64 major = 2;
     */
    major: bigint;
    /**
     * @generated from protobuf field: int64 minor = 3;
     */
    minor: bigint;
    /**
     * @generated from protobuf field: int64 patch = 4;
     */
    patch: bigint;
    /**
     * @generated from protobuf field: bool released = 5;
     */
    released: boolean;
    /**
     * @generated from protobuf field: string kind = 6;
     */
    kind: string;
    /**
     * @generated from protobuf field: repeated data.PatchChange changes = 7;
     */
    changes: PatchChange[];
}
/**
 * @generated from protobuf message data.PatchChange
 */
export interface PatchChange {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
    /**
     * @generated from protobuf field: string text = 3;
     */
    text: string;
}
/**
 * @generated from protobuf message data.CreatePatchRequest
 */
export interface CreatePatchRequest {
    /**
     * @generated from protobuf field: string kind = 1;
     */
    kind: string;
    /**
     * @generated from protobuf field: int64 major = 2;
     */
    major: bigint;
    /**
     * @generated from protobuf field: int64 minor = 3;
     */
    minor: bigint;
    /**
     * @generated from protobuf field: int64 patch = 4;
     */
    patch: bigint;
}
/**
 * @generated from protobuf message data.CreatePatchReply
 */
export interface CreatePatchReply {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
}
/**
 * @generated from protobuf message data.PatchRequest
 */
export interface PatchRequest {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
}
/**
 * @generated from protobuf message data.PatchReply
 */
export interface PatchReply {
    /**
     * @generated from protobuf field: data.Patch patch = 1;
     */
    patch?: Patch;
}
/**
 * @generated from protobuf message data.PatchesRequest
 */
export interface PatchesRequest {
    /**
     * @generated from protobuf field: string kind = 1;
     */
    kind: string;
}
/**
 * @generated from protobuf message data.PatchesReply
 */
export interface PatchesReply {
    /**
     * @generated from protobuf field: repeated data.Patch patches = 1;
     */
    patches: Patch[];
}
/**
 * @generated from protobuf message data.DeletePatchRequest
 */
export interface DeletePatchRequest {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
}
/**
 * @generated from protobuf message data.DeletePatchReply
 */
export interface DeletePatchReply {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
}
/**
 * @generated from protobuf message data.CreatePatchChangeRequest
 */
export interface CreatePatchChangeRequest {
    /**
     * @generated from protobuf field: int64 pcid = 1;
     */
    pcid: bigint;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
    /**
     * @generated from protobuf field: string text = 3;
     */
    text: string;
}
/**
 * @generated from protobuf message data.CreatePatchChangeReply
 */
export interface CreatePatchChangeReply {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
    /**
     * @generated from protobuf field: string text = 3;
     */
    text: string;
}
/**
 * @generated from protobuf message data.DeletePatchChangeRequest
 */
export interface DeletePatchChangeRequest {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
}
/**
 * @generated from protobuf message data.DeletePatchChangeReply
 */
export interface DeletePatchChangeReply {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
}
/**
 * @generated from protobuf message data.MarkPatchReleasedRequest
 */
export interface MarkPatchReleasedRequest {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
}
/**
 * @generated from protobuf message data.MarkPatchReleasedReply
 */
export interface MarkPatchReleasedReply {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
}
/**
 * @generated from protobuf message data.RevokePatchReleasedRequest
 */
export interface RevokePatchReleasedRequest {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
}
/**
 * @generated from protobuf message data.RevokePatchReleasedReply
 */
export interface RevokePatchReleasedReply {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
}
/**
 * @generated from protobuf message data.ReleasedPatchesRequest
 */
export interface ReleasedPatchesRequest {
    /**
     * @generated from protobuf field: string kind = 1;
     */
    kind: string;
}
/**
 * @generated from protobuf message data.ReleasedPatchesReply
 */
export interface ReleasedPatchesReply {
    /**
     * @generated from protobuf field: repeated data.Patch patches = 1;
     */
    patches: Patch[];
}
/**
 * @generated from protobuf message data.MostRecentPatchRequest
 */
export interface MostRecentPatchRequest {
    /**
     * @generated from protobuf field: string kind = 1;
     */
    kind: string;
}
/**
 * @generated from protobuf message data.MostRecentPatchReply
 */
export interface MostRecentPatchReply {
    /**
     * @generated from protobuf field: data.Patch patch = 1;
     */
    patch?: Patch;
}
/**
 * @generated from protobuf message data.AllRequestSummariesRequest
 */
export interface AllRequestSummariesRequest {
    /**
     * @generated from protobuf field: int64 pid = 1;
     */
    pid: bigint;
}
/**
 * @generated from protobuf message data.RequestSummary
 */
export interface RequestSummary {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: string type = 2;
     */
    type: string;
    /**
     * @generated from protobuf field: string status = 3;
     */
    status: string;
    /**
     * @generated from protobuf field: string user = 4;
     */
    user: string;
    /**
     * @generated from protobuf field: string reviewer = 5;
     */
    reviewer: string;
}
/**
 * @generated from protobuf message data.AllRequestSummariesReply
 */
export interface AllRequestSummariesReply {
    /**
     * @generated from protobuf field: repeated data.RequestSummary summaries = 1;
     */
    summaries: RequestSummary[];
}
/**
 * @generated from protobuf message data.RequestSummaryForPlayerRequest
 */
export interface RequestSummaryForPlayerRequest {
    /**
     * @generated from protobuf field: int64 pid = 1;
     */
    pid: bigint;
}
/**
 * @generated from protobuf message data.RequestSummaryForPlayer
 */
export interface RequestSummaryForPlayer {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: string status = 2;
     */
    status: string;
}
/**
 * @generated from protobuf message data.RequestSummaryForPlayerReply
 */
export interface RequestSummaryForPlayerReply {
}
// @generated message type with reflection information, may provide speed optimized methods
class Patch$Type extends MessageType<Patch> {
    constructor() {
        super("data.Patch", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "major", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "minor", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "patch", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "released", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "kind", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "changes", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PatchChange }
        ]);
    }
    create(value?: PartialMessage<Patch>): Patch {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.major = 0n;
        message.minor = 0n;
        message.patch = 0n;
        message.released = false;
        message.kind = "";
        message.changes = [];
        if (value !== undefined)
            reflectionMergePartial<Patch>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Patch): Patch {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* int64 major */ 2:
                    message.major = reader.int64().toBigInt();
                    break;
                case /* int64 minor */ 3:
                    message.minor = reader.int64().toBigInt();
                    break;
                case /* int64 patch */ 4:
                    message.patch = reader.int64().toBigInt();
                    break;
                case /* bool released */ 5:
                    message.released = reader.bool();
                    break;
                case /* string kind */ 6:
                    message.kind = reader.string();
                    break;
                case /* repeated data.PatchChange changes */ 7:
                    message.changes.push(PatchChange.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Patch, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* int64 major = 2; */
        if (message.major !== 0n)
            writer.tag(2, WireType.Varint).int64(message.major);
        /* int64 minor = 3; */
        if (message.minor !== 0n)
            writer.tag(3, WireType.Varint).int64(message.minor);
        /* int64 patch = 4; */
        if (message.patch !== 0n)
            writer.tag(4, WireType.Varint).int64(message.patch);
        /* bool released = 5; */
        if (message.released !== false)
            writer.tag(5, WireType.Varint).bool(message.released);
        /* string kind = 6; */
        if (message.kind !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.kind);
        /* repeated data.PatchChange changes = 7; */
        for (let i = 0; i < message.changes.length; i++)
            PatchChange.internalBinaryWrite(message.changes[i], writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.Patch
 */
export const Patch = new Patch$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PatchChange$Type extends MessageType<PatchChange> {
    constructor() {
        super("data.PatchChange", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PatchChange>): PatchChange {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.title = "";
        message.text = "";
        if (value !== undefined)
            reflectionMergePartial<PatchChange>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PatchChange): PatchChange {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string text */ 3:
                    message.text = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PatchChange, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string text = 3; */
        if (message.text !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.text);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.PatchChange
 */
export const PatchChange = new PatchChange$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePatchRequest$Type extends MessageType<CreatePatchRequest> {
    constructor() {
        super("data.CreatePatchRequest", [
            { no: 1, name: "kind", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "major", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "minor", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "patch", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<CreatePatchRequest>): CreatePatchRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.kind = "";
        message.major = 0n;
        message.minor = 0n;
        message.patch = 0n;
        if (value !== undefined)
            reflectionMergePartial<CreatePatchRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePatchRequest): CreatePatchRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string kind */ 1:
                    message.kind = reader.string();
                    break;
                case /* int64 major */ 2:
                    message.major = reader.int64().toBigInt();
                    break;
                case /* int64 minor */ 3:
                    message.minor = reader.int64().toBigInt();
                    break;
                case /* int64 patch */ 4:
                    message.patch = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePatchRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string kind = 1; */
        if (message.kind !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.kind);
        /* int64 major = 2; */
        if (message.major !== 0n)
            writer.tag(2, WireType.Varint).int64(message.major);
        /* int64 minor = 3; */
        if (message.minor !== 0n)
            writer.tag(3, WireType.Varint).int64(message.minor);
        /* int64 patch = 4; */
        if (message.patch !== 0n)
            writer.tag(4, WireType.Varint).int64(message.patch);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.CreatePatchRequest
 */
export const CreatePatchRequest = new CreatePatchRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePatchReply$Type extends MessageType<CreatePatchReply> {
    constructor() {
        super("data.CreatePatchReply", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<CreatePatchReply>): CreatePatchReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<CreatePatchReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePatchReply): CreatePatchReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePatchReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.CreatePatchReply
 */
export const CreatePatchReply = new CreatePatchReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PatchRequest$Type extends MessageType<PatchRequest> {
    constructor() {
        super("data.PatchRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<PatchRequest>): PatchRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<PatchRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PatchRequest): PatchRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PatchRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.PatchRequest
 */
export const PatchRequest = new PatchRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PatchReply$Type extends MessageType<PatchReply> {
    constructor() {
        super("data.PatchReply", [
            { no: 1, name: "patch", kind: "message", T: () => Patch }
        ]);
    }
    create(value?: PartialMessage<PatchReply>): PatchReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<PatchReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PatchReply): PatchReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* data.Patch patch */ 1:
                    message.patch = Patch.internalBinaryRead(reader, reader.uint32(), options, message.patch);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PatchReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* data.Patch patch = 1; */
        if (message.patch)
            Patch.internalBinaryWrite(message.patch, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.PatchReply
 */
export const PatchReply = new PatchReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PatchesRequest$Type extends MessageType<PatchesRequest> {
    constructor() {
        super("data.PatchesRequest", [
            { no: 1, name: "kind", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PatchesRequest>): PatchesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.kind = "";
        if (value !== undefined)
            reflectionMergePartial<PatchesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PatchesRequest): PatchesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string kind */ 1:
                    message.kind = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PatchesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string kind = 1; */
        if (message.kind !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.kind);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.PatchesRequest
 */
export const PatchesRequest = new PatchesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PatchesReply$Type extends MessageType<PatchesReply> {
    constructor() {
        super("data.PatchesReply", [
            { no: 1, name: "patches", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Patch }
        ]);
    }
    create(value?: PartialMessage<PatchesReply>): PatchesReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.patches = [];
        if (value !== undefined)
            reflectionMergePartial<PatchesReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PatchesReply): PatchesReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated data.Patch patches */ 1:
                    message.patches.push(Patch.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PatchesReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated data.Patch patches = 1; */
        for (let i = 0; i < message.patches.length; i++)
            Patch.internalBinaryWrite(message.patches[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.PatchesReply
 */
export const PatchesReply = new PatchesReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePatchRequest$Type extends MessageType<DeletePatchRequest> {
    constructor() {
        super("data.DeletePatchRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<DeletePatchRequest>): DeletePatchRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<DeletePatchRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePatchRequest): DeletePatchRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePatchRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.DeletePatchRequest
 */
export const DeletePatchRequest = new DeletePatchRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePatchReply$Type extends MessageType<DeletePatchReply> {
    constructor() {
        super("data.DeletePatchReply", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<DeletePatchReply>): DeletePatchReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<DeletePatchReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePatchReply): DeletePatchReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePatchReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.DeletePatchReply
 */
export const DeletePatchReply = new DeletePatchReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePatchChangeRequest$Type extends MessageType<CreatePatchChangeRequest> {
    constructor() {
        super("data.CreatePatchChangeRequest", [
            { no: 1, name: "pcid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreatePatchChangeRequest>): CreatePatchChangeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pcid = 0n;
        message.title = "";
        message.text = "";
        if (value !== undefined)
            reflectionMergePartial<CreatePatchChangeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePatchChangeRequest): CreatePatchChangeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 pcid */ 1:
                    message.pcid = reader.int64().toBigInt();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string text */ 3:
                    message.text = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePatchChangeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 pcid = 1; */
        if (message.pcid !== 0n)
            writer.tag(1, WireType.Varint).int64(message.pcid);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string text = 3; */
        if (message.text !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.text);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.CreatePatchChangeRequest
 */
export const CreatePatchChangeRequest = new CreatePatchChangeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePatchChangeReply$Type extends MessageType<CreatePatchChangeReply> {
    constructor() {
        super("data.CreatePatchChangeReply", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreatePatchChangeReply>): CreatePatchChangeReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.title = "";
        message.text = "";
        if (value !== undefined)
            reflectionMergePartial<CreatePatchChangeReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePatchChangeReply): CreatePatchChangeReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string text */ 3:
                    message.text = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePatchChangeReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string text = 3; */
        if (message.text !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.text);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.CreatePatchChangeReply
 */
export const CreatePatchChangeReply = new CreatePatchChangeReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePatchChangeRequest$Type extends MessageType<DeletePatchChangeRequest> {
    constructor() {
        super("data.DeletePatchChangeRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<DeletePatchChangeRequest>): DeletePatchChangeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<DeletePatchChangeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePatchChangeRequest): DeletePatchChangeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePatchChangeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.DeletePatchChangeRequest
 */
export const DeletePatchChangeRequest = new DeletePatchChangeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePatchChangeReply$Type extends MessageType<DeletePatchChangeReply> {
    constructor() {
        super("data.DeletePatchChangeReply", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<DeletePatchChangeReply>): DeletePatchChangeReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<DeletePatchChangeReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePatchChangeReply): DeletePatchChangeReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePatchChangeReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.DeletePatchChangeReply
 */
export const DeletePatchChangeReply = new DeletePatchChangeReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MarkPatchReleasedRequest$Type extends MessageType<MarkPatchReleasedRequest> {
    constructor() {
        super("data.MarkPatchReleasedRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<MarkPatchReleasedRequest>): MarkPatchReleasedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<MarkPatchReleasedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MarkPatchReleasedRequest): MarkPatchReleasedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MarkPatchReleasedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.MarkPatchReleasedRequest
 */
export const MarkPatchReleasedRequest = new MarkPatchReleasedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MarkPatchReleasedReply$Type extends MessageType<MarkPatchReleasedReply> {
    constructor() {
        super("data.MarkPatchReleasedReply", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<MarkPatchReleasedReply>): MarkPatchReleasedReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<MarkPatchReleasedReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MarkPatchReleasedReply): MarkPatchReleasedReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MarkPatchReleasedReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.MarkPatchReleasedReply
 */
export const MarkPatchReleasedReply = new MarkPatchReleasedReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RevokePatchReleasedRequest$Type extends MessageType<RevokePatchReleasedRequest> {
    constructor() {
        super("data.RevokePatchReleasedRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<RevokePatchReleasedRequest>): RevokePatchReleasedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<RevokePatchReleasedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RevokePatchReleasedRequest): RevokePatchReleasedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RevokePatchReleasedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.RevokePatchReleasedRequest
 */
export const RevokePatchReleasedRequest = new RevokePatchReleasedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RevokePatchReleasedReply$Type extends MessageType<RevokePatchReleasedReply> {
    constructor() {
        super("data.RevokePatchReleasedReply", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<RevokePatchReleasedReply>): RevokePatchReleasedReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        if (value !== undefined)
            reflectionMergePartial<RevokePatchReleasedReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RevokePatchReleasedReply): RevokePatchReleasedReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RevokePatchReleasedReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.RevokePatchReleasedReply
 */
export const RevokePatchReleasedReply = new RevokePatchReleasedReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReleasedPatchesRequest$Type extends MessageType<ReleasedPatchesRequest> {
    constructor() {
        super("data.ReleasedPatchesRequest", [
            { no: 1, name: "kind", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ReleasedPatchesRequest>): ReleasedPatchesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.kind = "";
        if (value !== undefined)
            reflectionMergePartial<ReleasedPatchesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReleasedPatchesRequest): ReleasedPatchesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string kind */ 1:
                    message.kind = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReleasedPatchesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string kind = 1; */
        if (message.kind !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.kind);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.ReleasedPatchesRequest
 */
export const ReleasedPatchesRequest = new ReleasedPatchesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReleasedPatchesReply$Type extends MessageType<ReleasedPatchesReply> {
    constructor() {
        super("data.ReleasedPatchesReply", [
            { no: 1, name: "patches", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Patch }
        ]);
    }
    create(value?: PartialMessage<ReleasedPatchesReply>): ReleasedPatchesReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.patches = [];
        if (value !== undefined)
            reflectionMergePartial<ReleasedPatchesReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReleasedPatchesReply): ReleasedPatchesReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated data.Patch patches */ 1:
                    message.patches.push(Patch.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReleasedPatchesReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated data.Patch patches = 1; */
        for (let i = 0; i < message.patches.length; i++)
            Patch.internalBinaryWrite(message.patches[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.ReleasedPatchesReply
 */
export const ReleasedPatchesReply = new ReleasedPatchesReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MostRecentPatchRequest$Type extends MessageType<MostRecentPatchRequest> {
    constructor() {
        super("data.MostRecentPatchRequest", [
            { no: 1, name: "kind", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MostRecentPatchRequest>): MostRecentPatchRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.kind = "";
        if (value !== undefined)
            reflectionMergePartial<MostRecentPatchRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MostRecentPatchRequest): MostRecentPatchRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string kind */ 1:
                    message.kind = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MostRecentPatchRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string kind = 1; */
        if (message.kind !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.kind);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.MostRecentPatchRequest
 */
export const MostRecentPatchRequest = new MostRecentPatchRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MostRecentPatchReply$Type extends MessageType<MostRecentPatchReply> {
    constructor() {
        super("data.MostRecentPatchReply", [
            { no: 1, name: "patch", kind: "message", T: () => Patch }
        ]);
    }
    create(value?: PartialMessage<MostRecentPatchReply>): MostRecentPatchReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<MostRecentPatchReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MostRecentPatchReply): MostRecentPatchReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* data.Patch patch */ 1:
                    message.patch = Patch.internalBinaryRead(reader, reader.uint32(), options, message.patch);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MostRecentPatchReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* data.Patch patch = 1; */
        if (message.patch)
            Patch.internalBinaryWrite(message.patch, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.MostRecentPatchReply
 */
export const MostRecentPatchReply = new MostRecentPatchReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AllRequestSummariesRequest$Type extends MessageType<AllRequestSummariesRequest> {
    constructor() {
        super("data.AllRequestSummariesRequest", [
            { no: 1, name: "pid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<AllRequestSummariesRequest>): AllRequestSummariesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pid = 0n;
        if (value !== undefined)
            reflectionMergePartial<AllRequestSummariesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AllRequestSummariesRequest): AllRequestSummariesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 pid */ 1:
                    message.pid = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AllRequestSummariesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 pid = 1; */
        if (message.pid !== 0n)
            writer.tag(1, WireType.Varint).int64(message.pid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.AllRequestSummariesRequest
 */
export const AllRequestSummariesRequest = new AllRequestSummariesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RequestSummary$Type extends MessageType<RequestSummary> {
    constructor() {
        super("data.RequestSummary", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "user", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "reviewer", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RequestSummary>): RequestSummary {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.type = "";
        message.status = "";
        message.user = "";
        message.reviewer = "";
        if (value !== undefined)
            reflectionMergePartial<RequestSummary>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RequestSummary): RequestSummary {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* string type */ 2:
                    message.type = reader.string();
                    break;
                case /* string status */ 3:
                    message.status = reader.string();
                    break;
                case /* string user */ 4:
                    message.user = reader.string();
                    break;
                case /* string reviewer */ 5:
                    message.reviewer = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RequestSummary, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* string type = 2; */
        if (message.type !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.type);
        /* string status = 3; */
        if (message.status !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.status);
        /* string user = 4; */
        if (message.user !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.user);
        /* string reviewer = 5; */
        if (message.reviewer !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.reviewer);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.RequestSummary
 */
export const RequestSummary = new RequestSummary$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AllRequestSummariesReply$Type extends MessageType<AllRequestSummariesReply> {
    constructor() {
        super("data.AllRequestSummariesReply", [
            { no: 1, name: "summaries", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => RequestSummary }
        ]);
    }
    create(value?: PartialMessage<AllRequestSummariesReply>): AllRequestSummariesReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.summaries = [];
        if (value !== undefined)
            reflectionMergePartial<AllRequestSummariesReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AllRequestSummariesReply): AllRequestSummariesReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated data.RequestSummary summaries */ 1:
                    message.summaries.push(RequestSummary.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AllRequestSummariesReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated data.RequestSummary summaries = 1; */
        for (let i = 0; i < message.summaries.length; i++)
            RequestSummary.internalBinaryWrite(message.summaries[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.AllRequestSummariesReply
 */
export const AllRequestSummariesReply = new AllRequestSummariesReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RequestSummaryForPlayerRequest$Type extends MessageType<RequestSummaryForPlayerRequest> {
    constructor() {
        super("data.RequestSummaryForPlayerRequest", [
            { no: 1, name: "pid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<RequestSummaryForPlayerRequest>): RequestSummaryForPlayerRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pid = 0n;
        if (value !== undefined)
            reflectionMergePartial<RequestSummaryForPlayerRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RequestSummaryForPlayerRequest): RequestSummaryForPlayerRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 pid */ 1:
                    message.pid = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RequestSummaryForPlayerRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 pid = 1; */
        if (message.pid !== 0n)
            writer.tag(1, WireType.Varint).int64(message.pid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.RequestSummaryForPlayerRequest
 */
export const RequestSummaryForPlayerRequest = new RequestSummaryForPlayerRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RequestSummaryForPlayer$Type extends MessageType<RequestSummaryForPlayer> {
    constructor() {
        super("data.RequestSummaryForPlayer", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RequestSummaryForPlayer>): RequestSummaryForPlayer {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.status = "";
        if (value !== undefined)
            reflectionMergePartial<RequestSummaryForPlayer>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RequestSummaryForPlayer): RequestSummaryForPlayer {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toBigInt();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RequestSummaryForPlayer, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.RequestSummaryForPlayer
 */
export const RequestSummaryForPlayer = new RequestSummaryForPlayer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RequestSummaryForPlayerReply$Type extends MessageType<RequestSummaryForPlayerReply> {
    constructor() {
        super("data.RequestSummaryForPlayerReply", []);
    }
    create(value?: PartialMessage<RequestSummaryForPlayerReply>): RequestSummaryForPlayerReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RequestSummaryForPlayerReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RequestSummaryForPlayerReply): RequestSummaryForPlayerReply {
        return target ?? this.create();
    }
    internalBinaryWrite(message: RequestSummaryForPlayerReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message data.RequestSummaryForPlayerReply
 */
export const RequestSummaryForPlayerReply = new RequestSummaryForPlayerReply$Type();
/**
 * @generated ServiceType for protobuf service data.Wish
 */
export const Wish = new ServiceType("data.Wish", [
    { name: "CreatePatch", options: {}, I: CreatePatchRequest, O: CreatePatchReply },
    { name: "Patch", options: {}, I: PatchRequest, O: PatchReply },
    { name: "Patches", options: {}, I: PatchesRequest, O: PatchesReply },
    { name: "DeletePatch", options: {}, I: DeletePatchRequest, O: DeletePatchReply },
    { name: "CreatePatchChange", options: {}, I: CreatePatchChangeRequest, O: CreatePatchChangeReply },
    { name: "DeletePatchChange", options: {}, I: DeletePatchChangeRequest, O: DeletePatchChangeReply },
    { name: "MarkPatchReleased", options: {}, I: MarkPatchReleasedRequest, O: MarkPatchReleasedReply },
    { name: "RevokePatchReleased", options: {}, I: RevokePatchReleasedRequest, O: RevokePatchReleasedReply },
    { name: "ReleasedPatches", options: {}, I: ReleasedPatchesRequest, O: ReleasedPatchesReply },
    { name: "MostRecentPatch", options: {}, I: MostRecentPatchRequest, O: MostRecentPatchReply },
    { name: "AllRequestSummaries", options: {}, I: AllRequestSummariesRequest, O: AllRequestSummariesReply },
    { name: "RequestSummaryForPlayer", options: {}, I: RequestSummaryForPlayerRequest, O: RequestSummaryForPlayerReply }
]);
